Repository ISPP-G-8/infantem, pull requests merged in 2025-03, with the labels that each got.

#100 #34 Usuarios
  src/main/java/com/isppG8/infantem/usuario/Usuario.java
  src/main/java/com/isppG8/infantem/usuario/UsuarioController.java
  src/main/java/com/isppG8/infantem/usuario/UsuarioRepository.java
  src/main/java/com/isppG8/infantem/usuario/UsuarioService.java
Labels: enhancement

#126 Feat/disease vaccines
  src/main/java/com/isppG8/infantem/infantem/baby/Baby.java
  src/main/java/com/isppG8/infantem/infantem/disease/Disease.java
  src/main/java/com/isppG8/infantem/infantem/disease/DiseaseController.java
  src/main/java/com/isppG8/infantem/infantem/disease/DiseaseRepository.java
  src/main/java/com/isppG8/infantem/infantem/disease/DiseaseService.java
  src/main/java/com/isppG8/infantem/infantem/vaccine/Vaccine.java
  src/main/java/com/isppG8/infantem/infantem/vaccine/VaccineController.java
  src/main/java/com/isppG8/infantem/infantem/vaccine/VaccineRepository.java
  src/main/java/com/isppG8/infantem/infantem/vaccine/VaccineService.java
Labels: enhancement

#134 Feat/recipe recommendations backend
  populate_database/populate_database.sql
  populate_database/scipt sql para popular con datos de prueba.txt
  src/main/java/com/isppG8/infantem/infantem/intake/Recipe.java
  src/main/java/com/isppG8/infantem/infantem/recipe/Recipe.java
  src/main/java/com/isppG8/infantem/infantem/recipe/RecipeController.java
  src/main/java/com/isppG8/infantem/infantem/recipe/RecipeRepository.java
  src/main/java/com/isppG8/infantem/infantem/recipe/RecipeService.java
  src/main/java/com/isppG8/infantem/infantem/user/User.java
Labels: enhancement

#144 Refactor navbar to stack navigation
  frontend/app/(tabs)/_layout.tsx
  frontend/app/(tabs)/account/_layout.tsx
  frontend/app/(tabs)/account/index.tsx
  frontend/app/(tabs)/allergens/_layout.tsx
  frontend/app/(tabs)/allergens/index.tsx
  frontend/app/(tabs)/food/_layout.tsx
  frontend/app/(tabs)/food/index.tsx
  frontend/app/(tabs)/recipes/_layout.tsx
  frontend/app/(tabs)/recipes/detail.tsx
  frontend/app/(tabs)/recipes/index.tsx
  frontend/app/+not-found.tsx
  frontend/app/_layout.tsx
  frontend/app/appStyleSamples.tsx
  frontend/app/index.tsx
  frontend/app/login.tsx
  frontend/app/profile.tsx
  frontend/components/NavBar.tsx
Labels: bug

#216 feat: añadir flujo de trabajo de Codacy
  .github/workflows/codacy.yml
Labels: enhancement

#225 feat: Add info.yml for governify Refs #195
  info.yml
Labels: documentation

#227 fix: Update info.yml Refs #195
  info.yml
Labels: documentation
